# Generated by Django 5.0.2 on 2024-05-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='photo_file_path',
            field=models.CharField(default='defalt.jpg', max_length=300),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(default='Activity', max_length=200),
        ),
    ]
