# Generated by Django 4.2.6 on 2024-05-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='photo_file_path',
            field=models.CharField(default='activity_photos/defalt.jpg', max_length=300),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
