# Generated by Django 4.2.8 on 2024-03-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_audio',
            new_name='activity_feedback_audio',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_question_answers',
            new_name='activity_feedback_question_answers',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_text',
            new_name='activity_feedback_text',
        ),
        migrations.AddField(
            model_name='feedback',
            name='leader_feedback_audio',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='leader_feedback_question_answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='leader_feedback_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
