# Generated by Django 4.2.6 on 2024-05-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_activity_photo_file_path_activity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='photo_file_path',
            field=models.CharField(default='defalt.jpg', max_length=300),
        ),
    ]
