# Generated by Django 4.2.13 on 2024-05-13 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLeaderVote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.activityleader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
