# Generated by Django 4.2.13 on 2024-05-13 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaderVoteAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityleadervote',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
